# Z Flip5 Display and Foldable Features
# Optimizes display settings and foldable-specific features

LOG_BEGIN "Adding Z Flip5 Display & Foldable Features"

# Display features
FF "DISPLAY_SUPPORT_ADAPTIVE_REFRESH_RATE" "TRUE"
FF "DISPLAY_CONFIG_REFRESH_RATE" "1-120"
FF "DISPLAY_SUPPORT_OUTDOOR_MODE" "TRUE"
FF "DISPLAY_SUPPORT_ADAPTIVE_COLOR_TONE" "TRUE"
FF "DISPLAY_SUPPORT_EYE_COMFORT_SHIELD" "TRUE"
FF "DISPLAY_SUPPORT_BRIGHTNESS_BOOST" "TRUE"

# Foldable-specific features
FF "COMMON_SUPPORT_FLEX_MODE" "TRUE"
FF "COMMON_SUPPORT_COVER_SCREEN" "TRUE"
FF "COMMON_SUPPORT_FLEX_MODE_PANEL" "TRUE"
FF "COMMON_SUPPORT_CONTINUITY" "TRUE"
FF "COMMON_SUPPORT_APP_CONTINUITY" "TRUE"

# Cover screen features
FF "COVER_SCREEN_SUPPORT_WIDGETS" "TRUE"
FF "COVER_SCREEN_SUPPORT_NOTIFICATIONS" "TRUE"
FF "COVER_SCREEN_SUPPORT_QUICK_ACTIONS" "TRUE"
FF "COVER_SCREEN_SUPPORT_CAMERA_PREVIEW" "TRUE"
FF "COVER_SCREEN_SUPPORT_MUSIC_CONTROL" "TRUE"

# Flex Mode optimizations
FF "FLEX_MODE_SUPPORT_VIDEO_CALLS" "TRUE"
FF "FLEX_MODE_SUPPORT_CAMERA" "TRUE"
FF "FLEX_MODE_SUPPORT_GALLERY" "TRUE"
FF "FLEX_MODE_SUPPORT_YOUTUBE" "TRUE"
FF "FLEX_MODE_SUPPORT_DUAL_PREVIEW" "TRUE"

# Multi-window and split screen
FF "COMMON_SUPPORT_MULTI_WINDOW" "TRUE"
FF "COMMON_SUPPORT_SPLIT_SCREEN" "TRUE"
FF "COMMON_SUPPORT_POPUP_VIEW" "TRUE"
FF "COMMON_SUPPORT_FLOATING_WINDOW" "TRUE"

# Display quality
FF "DISPLAY_CONFIG_RESOLUTION" "FHD_PLUS"
FF "DISPLAY_SUPPORT_HDR10_PLUS" "TRUE"
FF "DISPLAY_SUPPORT_DYNAMIC_AMOLED" "TRUE"

# Screen recording on cover screen
FF "COVER_SCREEN_SUPPORT_SCREEN_RECORD" "TRUE"

LOG_END "Z Flip5 Display & Foldable Features Added"
