# Z Flip5 AI Features Enhancement
# Adds AI features compatible with Z Flip5

LOG_BEGIN "Adding Z Flip5 AI Features"

# Enable AI features for Z Flip5
# Z Flip5 (SM-F731B) supports AI features with Snapdragon 8 Gen 2
if [[ "$MODEL" == SM-F73* ]] || [[ "$EXTRA_MODEL" == SM-S93* ]] || [[ "$EXTRA_MODEL" == SM-F73* ]]; then

# AI Core features
FF "COMMON_SUPPORT_AI_AGENT" "TRUE"
FF "COMMON_CONFIG_AI_VERSION" "20253"
FF "COMMON_CONFIG_AWESOME_INTELLIGENCE" "202501"

# Generative AI
FF "GENAI_CONFIG_LLM_VERSION" "0.40"
FF "GENAI_SUPPORT_C2PA" "TRUE"
FF "GENAI_CONFIG_FOUNDATION_MODEL" "3B"
FF "GENAI_SUPPORT_OFFLINE_LANGUAGEMODEL" "TRUE"

# AI Photo and Video
FF "MMFW_SUPPORT_AI_UPSCALER" "TRUE"
FF "MMFW_SUPPORT_AI_PHOTO_ENHANCEMENT" "TRUE"
FF "MMFW_SUPPORT_AI_VIDEO_ENHANCEMENT" "TRUE"
FF "MMFW_SUPPORT_MEDIA_CONTEXT_ANALYZER" "TRUE"

# AI in Camera
FF "CAMERA_SUPPORT_AI_SCENE_OPTIMIZER" "TRUE"
FF "CAMERA_SUPPORT_AI_PHOTO" "TRUE"
FF "CAMERA_SUPPORT_AI_ZOOM" "TRUE"
FF "CAMERA_SUPPORT_AI_PORTRAIT" "TRUE"

# AI in Gallery
FF "GALLERY_SUPPORT_AI_SEARCH" "TRUE"
FF "GALLERY_SUPPORT_AI_SUGGESTIONS" "TRUE"
FF "GALLERY_SUPPORT_AI_EDITING" "TRUE"

# Bixby AI
FF "BIXBY_SUPPORT_AI_VOICE" "TRUE"
FF "BIXBY_SUPPORT_AI_VISION" "TRUE"
FF "BIXBY_SUPPORT_AI_ROUTINES" "TRUE"

# Smart suggestions
FF "FRAMEWORK_SUPPORT_SMART_SUGGESTIONS" "TRUE"
FF "FRAMEWORK_SUPPORT_PERSONALIZED_DATA_CORE" "TRUE"

# AI Wallpapers
FF "WALLPAPER_SUPPORT_AI_GENERATION" "TRUE"
FF "WALLPAPER_SUPPORT_AI_ANIMATION" "TRUE"

fi

LOG_END "Z Flip5 AI Features Added"
