# Z Flip5 CSC (Carrier Specific Features) Enhancements
# Adds additional CSC features for Z Flip5

LOG_BEGIN "Adding Z Flip5 CSC Features"

# Camera CSC features
FF "CSCFEATURE_CAMERA_DEFAULT_QUALITY" "superfine"
FF "CSCFEATURE_CAMERA_ENABLE_DURING_CALL" "TRUE"
FF "CSCFEATURE_CAMERA_CAMCORDER_DO_NOT_PAUSE_MUSIC" "TRUE"
FF "CSCFEATURE_CAMERA_CAMERA_FLICKER" "60hz"

# Gallery CSC features
FF "CSCFEATURE_GALLERY_SUPPORT_ALIVE_ZOOM" "TRUE"
FF "CSCFEATURE_GALLERY_SUPPORT_VIDEO_PLAYER" "TRUE"

# Message CSC features
FF "CSCFEATURE_MESSAGE_SUPPORT_USEFUL_CARD" "TRUE"
FF "CSCFEATURE_MESSAGE_SUPPORT_RCS" "TRUE"

# Voice Call CSC features
FF "CSCFEATURE_VOICECALL_CONFIG_RECORDING" "RecordingAllowed"
FF "CSCFEATURE_VOICECALL_ENABLE_DISPLAY_SDN_NAME" "TRUE"

# Video Call CSC features
FF "CSCFEATURE_VT_CONFIG_BEARER" "-CSVT"
FF "CSCFEATURE_CONTACT_SUPPORT_DUO_VIDEO_CALL" "TRUE"

# Contact CSC features
FF "CSCFEATURE_CONTACT_ENABLE_DYN_CALLER_ID" "TRUE"
FF "CSCFEATURE_CONTACT_CONFIG_SVC_PROVIDER" "whitepages,off"

# Clock CSC features
FF "CSCFEATURE_CLOCK_ENABLE_AUTO_POWER_ON_OFF" "TRUE"
FF "CSCFEATURE_CLOCK_SUPPORT_ALARM_OPTION_MENU" "TRUE"
FF "CSCFEATURE_CLOCK_SUPPORT_ALARM_SOUND_MENU" "TRUE"
FF "CSCFEATURE_CLOCK_SUPPORT_TIMER_RESET_BUTTON" "TRUE"

# SystemUI CSC features
FF "CSCFEATURE_SYSTEMUI_CONFIG_OVERRIDE_DATA_ICON" "LTE"
FF "CSCFEATURE_SYSTEMUI_SUPPORT_DATA_USAGE_VIEW" "TRUE"

# Framework CSC features
FF "CSCFEATURE_FRAMEWORK_SUPPORT_DATA_MODE_SWITCH" "TRUE"

# Common CSC features
FF "CSCFEATURE_COMMON_ENHANCE_IMAGE_QUALITY" "TRUE"
FF "CSCFEATURE_COMMON_SUPPORT_PRIVATE_MODE" "TRUE"
FF "CSCFEATURE_COMMON_SUPPORT_Z_PROJECT_FUNCTION" "TRUE"

# Settings CSC features
FF "CSCFEATURE_SETTING_CONFIG_TYPE_HELP" "0"
FF "CSCFEATURE_SETTING_ENABLE_HW_VERSION_DISPLAY" "TRUE"
FF "CSCFEATURE_SETTING_SUPPORT_ELABEL_MANUFACTURER" "astrorom"
FF "CSCFEATURE_SETTING_SUPPORT_REGULATORY_INFO" "FALSE"

# Smart Manager CSC features
FF "CSCFEATURE_SMARTMANAGER_CONFIG_DASHBOARD" "dual_dashboard"
FF "CSCFEATURE_SMARTMANAGER_CONFIG_SUB_FEATURES" "applock|appcleanner|autolaunch|autorestart|devicesecurity|storageclean|backgroundapp|UDS|UDS2|applicationpermission|networkpowersaving|notificationmanager|trafficmanager|roguepopup|data_compression|cstyle"
FF "CSCFEATURE_SMARTMANAGER_DISABLE_ANTI_MALWARE" "TRUE"

# WiFi CSC features
FF "CSCFEATURE_WIFI_SUPPORT_BLOCK_SKIP_FOR_SETUP" "FALSE"
FF "CSCFEATURE_WIFI_SUPPORT_NETWORK_CONNECTIONS_REQUIRED" "FALSE"

# NFC CSC features
FF "CSCFEATURE_NFC_CONFIG_READER_MODE_UI" "KOREA"

LOG_END "Z Flip5 CSC Features Added"
