# Z Flip5 Performance Optimizations
# Enhances performance, gaming, and system responsiveness

LOG_BEGIN "Adding Z Flip5 Performance Optimizations"

# Gaming performance
FF "GAME_CONFIG_PERFORMANCE_MODE" "HIGH"
FF "GAME_SUPPORT_GAME_BOOSTER" "TRUE"
FF "GAME_SUPPORT_GAME_TOOLS" "TRUE"
FF "GAME_SUPPORT_HIGH_FPS" "TRUE"
FF "GAME_SUPPORT_120FPS_MODE" "TRUE"
FF "GAME_SUPPORT_GRAPHICS_PLUS" "TRUE"
FF "GAME_SUPPORT_ALTERNATIVE_GAME_PERFORMANCE" "TRUE"

# System performance
FF "SYSTEM_CONFIG_CPU_BOOST" "TRUE"
FF "SYSTEM_CONFIG_GPU_BOOST" "TRUE"
FF "SYSTEM_SUPPORT_PERFORMANCE_MODE" "TRUE"
FF "SYSTEM_SUPPORT_ADAPTIVE_PERFORMANCE" "TRUE"

# Memory and RAM optimization
FF "SYSTEM_CONFIG_MEMORY_OPTIMIZATION" "TRUE"
FF "SYSTEM_SUPPORT_RAM_PLUS" "TRUE"
FF "SYSTEM_CONFIG_RAM_PLUS_SIZE" "8GB"

# Thermal management
FF "SYSTEM_SUPPORT_LOW_HEAT_MODE" "TRUE"
FF "SYSTEM_SUPPORT_THERMAL_MANAGEMENT" "TRUE"
FF "SYSTEM_CONFIG_THERMAL_THROTTLE" "FALSE"

# Battery optimization
FF "BATTERY_SUPPORT_ADAPTIVE_BATTERY" "TRUE"
FF "BATTERY_SUPPORT_POWER_SAVING_MODE" "TRUE"
FF "BATTERY_SUPPORT_ULTRA_POWER_SAVING" "TRUE"
FF "BATTERY_SUPPORT_WIRELESS_POWER_SHARE" "TRUE"

# App launch optimization
FF "SYSTEM_SUPPORT_APP_LAUNCH_BOOST" "TRUE"
FF "SYSTEM_SUPPORT_QUICK_LAUNCH" "TRUE"
FF "SYSTEM_CONFIG_APP_PRELOAD" "TRUE"

# Network performance
FF "NETWORK_SUPPORT_5G_OPTIMIZATION" "TRUE"
FF "NETWORK_SUPPORT_WIFI_6E" "TRUE"
FF "NETWORK_SUPPORT_DUAL_SIM_5G" "TRUE"

# Storage optimization
FF "STORAGE_SUPPORT_UFS_OPTIMIZATION" "TRUE"
FF "STORAGE_SUPPORT_TRIM" "TRUE"

# Game Driver (already in stock.sh, but ensure it's enabled)
FF "GAME_CONFIG_DRIVER_VERSION" "SM8550"

LOG_END "Z Flip5 Performance Optimizations Added"
