# Z Flip5 Additional Features
# Extra features and enhancements specific to Z Flip5

LOG_BEGIN "Adding Z Flip5 Extra Features"

# Samsung Pay and Wallet
FF "COMMON_SUPPORT_SAMSUNG_PAY" "TRUE"
FF "COMMON_SUPPORT_SAMSUNG_WALLET" "TRUE"
FF "COMMON_SUPPORT_NFC_PAYMENT" "TRUE"

# Bixby and Voice features
FF "BIXBY_SUPPORT_VOICE_WAKEUP" "TRUE"
FF "BIXBY_SUPPORT_VISION" "TRUE"
FF "BIXBY_SUPPORT_ROUTINE" "TRUE"

# Samsung Health and Fitness
FF "HEALTH_SUPPORT_HEART_RATE" "TRUE"
FF "HEALTH_SUPPORT_STRESS_MONITOR" "TRUE"
FF "HEALTH_SUPPORT_SLEEP_TRACKING" "TRUE"
FF "HEALTH_SUPPORT_WORKOUT_DETECTION" "TRUE"

# Smart features
FF "COMMON_SUPPORT_SMART_STAY" "TRUE"
FF "COMMON_SUPPORT_SMART_ROTATION" "TRUE"
FF "COMMON_SUPPORT_SMART_PAUSE" "TRUE"
FF "COMMON_SUPPORT_SMART_SCROLL" "TRUE"
FF "COMMON_SUPPORT_AIR_GESTURE" "TRUE"
FF "COMMON_SUPPORT_AIR_VIEW" "TRUE"

# Edge features (for cover screen)
FF "EDGE_SUPPORT_EDGE_PANEL" "TRUE"
FF "EDGE_SUPPORT_EDGE_LIGHTING" "TRUE"
FF "EDGE_SUPPORT_EDGE_TOUCH" "TRUE"
FF "EDGE_SUPPORT_QUICK_TOOLS" "TRUE"

# Secure Folder and Knox features (patched)
FF "KNOX_SUPPORT_SECURE_FOLDER" "TRUE"
FF "KNOX_SUPPORT_PRIVATE_MODE" "TRUE"

# DeX support (if applicable)
FF "COMMON_SUPPORT_DEX" "TRUE"
FF "COMMON_SUPPORT_WIRELESS_DEX" "TRUE"

# Link to Windows
FF "COMMON_SUPPORT_LINK_TO_WINDOWS" "TRUE"
FF "COMMON_SUPPORT_PHONE_LINK" "TRUE"

# Quick Share and Nearby Share
FF "COMMON_SUPPORT_QUICK_SHARE" "TRUE"
FF "COMMON_SUPPORT_NEARBY_SHARE" "TRUE"
FF "COMMON_SUPPORT_SMART_VIEW" "TRUE"

# Camera cover screen widgets
FF "COVER_SCREEN_SUPPORT_CAMERA_WIDGET" "TRUE"
FF "COVER_SCREEN_SUPPORT_QUICK_ACTIONS" "TRUE"

# Always On Display enhancements
FF "DISPLAY_SUPPORT_AOD" "TRUE"
FF "DISPLAY_SUPPORT_AOD_COVER_SCREEN" "TRUE"
FF "DISPLAY_SUPPORT_AOD_NOTIFICATIONS" "TRUE"
FF "DISPLAY_SUPPORT_AOD_MUSIC_CONTROL" "TRUE"

# One UI optimizations
FF "LAUNCHER_SUPPORT_GOOD_LOCK" "TRUE"
FF "LAUNCHER_SUPPORT_THEME_PARK" "TRUE"
FF "LAUNCHER_SUPPORT_NICE_CATCH" "TRUE"

# Sound features
FF "SOUND_SUPPORT_DOLBY_ATMOS" "TRUE"
FF "SOUND_SUPPORT_AKG_TUNING" "TRUE"
FF "SOUND_SUPPORT_ADAPTIVE_SOUND" "TRUE"
FF "SOUND_SUPPORT_SURROUND_SOUND" "TRUE"

# Haptic feedback
FF "COMMON_SUPPORT_ADAPTIVE_HAPTIC" "TRUE"
FF "COMMON_SUPPORT_HAPTIC_FEEDBACK" "TRUE"

LOG_END "Z Flip5 Extra Features Added"
